import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 40,
    },
    loader: {
        marginTop: 100,
    },
    summaryCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 20,
        marginTop: 10,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.06,
        shadowRadius: 16,
        elevation: 4,
    },
    summaryTitle: {
        fontSize: 14,
        color: '#666666',
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: 4,
    },
    netBalanceAmount: {
        fontSize: 32,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 16,
        letterSpacing: -0.5,
    },
    splitSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 16,
        paddingVertical: 14,
        paddingHorizontal: 10,
    },
    moneyBox: {
        flex: 1,
        alignItems: 'center',
    },
    divider: {
        width: 1,
        height: '80%',
        backgroundColor: '#EAEAEA',
    },
    moneyLabel: {
        fontSize: 12,
        color: '#888888',
        fontWeight: '500',
        marginBottom: 4,
    },
    moneyValue: {
        fontSize: 16,
        fontWeight: '700',
    },
    searchContainer: {
        marginBottom: 20,
    },
    searchInput: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 15,
        color: '#1A1A1A',
        borderWidth: 1,
        borderColor: '#EAEAEA',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
        elevation: 2,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1A1A1A',
        marginBottom: 14,
    },
    emptyText: {
        textAlign: 'center',
        color: '#888888',
        marginTop: 40,
        fontSize: 15,
    },
    friendCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.03,
        shadowRadius: 8,
        elevation: 2,
    },
    friendLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 10,
    },
    avatarPlaceholder: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#4361EE20',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    avatarText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#4361EE',
    },
    friendDetails: {
        flex: 1,
    },
    friendName: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1A1A1A',
        marginBottom: 2,
    },
    friendEmail: {
        fontSize: 12,
        color: '#888888',
    },
    friendRight: {
        alignItems: 'flex-end',
        justifyContent: 'center',
    },
    balanceContainer: {
        alignItems: 'flex-end',
        marginBottom: 4,
    },
    balanceLabel: {
        fontSize: 11,
        color: '#888888',
        fontWeight: '500',
        marginBottom: 2,
    },
    balanceAmount: {
        fontSize: 15,
        fontWeight: '700',
    },
    settledText: {
        fontSize: 14,
        color: '#888888',
        fontWeight: '600',
    },
    settleButton: {
        backgroundColor: '#E1E7FF',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        marginTop: 4,
        borderWidth: 1,
        borderColor: '#C7D2FE',
    },
    settleButtonText: {
        color: '#4361EE',
        fontSize: 12,
        fontWeight: '700',
    },
});
