import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    scrollContent: {
        paddingBottom: 40,
    },
    loader: {
        marginTop: 100,
    },
    summaryBanner: {
        backgroundColor: '#4361EE',
        paddingHorizontal: 24,
        paddingTop: 24,
        paddingBottom: 36,
    },
    summaryBannerTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: 'rgba(255,255,255,0.7)',
        marginBottom: 4,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    netBalanceAmount: {
        fontSize: 42,
        fontWeight: '800',
        color: '#FFFFFF',
        letterSpacing: -1.5,
        marginBottom: 24,
    },
    summaryStatsRow: {
        flexDirection: 'row',
        gap: 12,
    },
    summaryStatBox: {
        flex: 1,
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 14,
        padding: 14,
    },
    summaryStatLabel: {
        fontSize: 11,
        color: 'rgba(255,255,255,0.7)',
        fontWeight: '600',
        marginBottom: 6,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    summaryStatValue: {
        fontSize: 20,
        fontWeight: '800',
        color: '#FFFFFF',
    },
    listSection: {
        paddingHorizontal: 20,
        marginTop: -18,
    },
    searchContainer: {
        marginBottom: 20,
    },
    searchInput: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        paddingHorizontal: 16,
        paddingVertical: 13,
        fontSize: 15,
        color: '#1A1A1A',
        borderWidth: 1,
        borderColor: '#EAEAEA',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
        elevation: 2,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 14,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1A1A1A',
    },
    friendCountBadge: {
        backgroundColor: '#EBF0FF',
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 4,
    },
    friendCountBadgeText: {
        fontSize: 13,
        fontWeight: '700',
        color: '#4361EE',
    },
    emptyText: {
        textAlign: 'center',
        color: '#888888',
        marginTop: 40,
        fontSize: 15,
    },
    friendCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 18,
        padding: 16,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#4361EE',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    friendLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 10,
    },
    avatarPlaceholder: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#EBF0FF',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
    },
    avatarText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#4361EE',
    },
    friendDetails: {
        flex: 1,
    },
    friendName: {
        fontSize: 15,
        fontWeight: '700',
        color: '#1A1A1A',
        marginBottom: 3,
    },
    friendEmail: {
        fontSize: 12,
        color: '#888888',
        fontWeight: '500',
    },
    friendRight: {
        alignItems: 'flex-end',
        justifyContent: 'center',
    },
    balanceContainer: {
        alignItems: 'flex-end',
        marginBottom: 6,
    },
    balanceLabel: {
        fontSize: 11,
        color: '#888888',
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 0.4,
        marginBottom: 2,
    },
    balanceAmount: {
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: -0.3,
    },
    settledText: {
        fontSize: 13,
        color: '#228c3bff',
        fontWeight: '700',
        marginBottom: 4,
    },
    settleButton: {
        backgroundColor: '#EBF0FF',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#C7D2FE',
    },
    settleButtonText: {
        color: '#4361EE',
        fontSize: 12,
        fontWeight: '700',
    },

    summaryCard: { backgroundColor: '#FFFFFF' },
    summaryTitle: { fontSize: 14, color: '#888', fontWeight: '600' },
    splitSection: { flexDirection: 'row' },
    moneyBox: { flex: 1 },
    divider: { width: 1, backgroundColor: '#EAEAEA' },
    moneyLabel: { fontSize: 12, color: '#888888' },
    moneyValue: { fontSize: 16, fontWeight: '700' },
});
