import { StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 40,
    },
    loader: {
        marginTop: 100,
    },
    summaryCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 24,
        marginTop: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.08,
        shadowRadius: 16,
        elevation: 6,
    },
    summaryTitle: {
        fontSize: 15,
        color: '#666666',
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: 8,
    },
    totalAmount: {
        fontSize: 40,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 24,
        letterSpacing: -1,
    },
    splitSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 16,
        padding: 16,
    },
    moneyBox: {
        flex: 1,
        alignItems: 'center',
    },
    divider: {
        width: 1,
        height: '100%',
        backgroundColor: '#E0E0E0',
        marginHorizontal: 16,
    },
    moneyLabel: {
        fontSize: 13,
        color: '#888888',
        fontWeight: '500',
        marginBottom: 6,
    },
    moneyValue: {
        fontSize: 18,
        fontWeight: '700',
    },
    groupsSection: {
        marginTop: 32,
    },
    groupsHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    groupsTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1A1A1A',
    },
    seeAllText: {
        fontSize: 14,
        color: '#4361EE',
        fontWeight: '600',
    },
    groupsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    groupBox: {
        width: '48%',
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
        elevation: 3,
    },
    createGroupBox: {
        width: '48%',
        backgroundColor: '#F0F3FF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E1E7FF',
        borderStyle: 'dashed',
    },
    groupIconContainer: {
        width: 48,
        height: 48,
        backgroundColor: '#F5F5F5',
        borderRadius: 24,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
    },
    createIconContainer: {
        width: 48,
        height: 48,
        backgroundColor: '#4361EE',
        borderRadius: 24,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
    },
    groupIcon: {
        fontSize: 24,
    },
    createIcon: {
        fontSize: 24,
        color: '#FFFFFF',
        fontWeight: '300',
    },
    groupName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333333',
        textAlign: 'center',
    },
    logoutButton: {
        marginTop: 30,
        paddingVertical: 14,
        borderRadius: 12,
        backgroundColor: '#FFF0F0',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#FFE0E0',
    },
    logoutText: {
        color: '#E53E3E',
        fontSize: 16,
        fontWeight: '700',
    },
});
