import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    container: {
        flex: 1,
    },
    innerContainer: {
        flex: 1,
        justifyContent: 'space-between',
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingTop: 10,
        paddingBottom: 40,
    },
    inputGroup: {
        marginBottom: 20,
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333333',
        marginBottom: 8,
    },
    input: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 16,
        color: '#333',
        borderWidth: 1,
        borderColor: '#E0E0E0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
        textAlign: 'center',
        justifyContent: 'center',
        alignItems: 'center',
    },
    amountInput: {
        fontSize: 32,
        fontWeight: '800',
        textAlign: 'center',
        paddingVertical: 20,
        color: '#4361EE',
    },
    splitTypeContainer: {
        flexDirection: 'row',
        backgroundColor: '#E1E7FF',
        borderRadius: 12,
        padding: 4,
        marginBottom: 20,
    },
    splitTypeButton: {
        flex: 1,
        paddingVertical: 10,
        alignItems: 'center',
        borderRadius: 8,
    },
    activeSplitType: {
        backgroundColor: '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    splitTypeText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#4361EE',
    },
    activeSplitTypeText: {
        color: '#4361EE',
    },
    memberSelectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1A1A1A',
        marginBottom: 12,
    },
    memberItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#FFFFFF',
        padding: 12,
        borderRadius: 12,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    activeMemberItem: {
        borderColor: '#4361EE',
        backgroundColor: '#F0F3FF',
    },
    memberInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    checkbox: {
        width: 22,
        height: 22,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: '#4361EE',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    checkboxChecked: {
        backgroundColor: '#4361EE',
    },
    checkmark: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '900',
    },
    memberName: {
        fontSize: 15,
        fontWeight: '600',
        color: '#333333',
    },
    memberEmail: {
        fontSize: 12,
        color: '#888888',
    },
    exactAmountInput: {
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 6,
        width: 80,
        textAlign: 'right',
        fontSize: 14,
        fontWeight: '700',
        color: '#4361EE',
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    paidByContainer: {
        marginBottom: 24,
    },
    paidByScroll: {
        paddingVertical: 4,
    },
    paidByButton: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        marginRight: 10,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        alignItems: 'center',
        justifyContent: 'center',
    },
    activePaidByButton: {
        backgroundColor: '#4361EE',
        borderColor: '#4361EE',
    },
    paidByText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666666',
    },
    activePaidByText: {
        color: '#FFFFFF',
    },
    footer: {
        paddingHorizontal: 24,
        paddingBottom: 30,
        paddingTop: 10,
        backgroundColor: '#F8F9FA',
    },
    createButton: {
        backgroundColor: '#4361EE',
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#4361EE',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    createButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
    },
});
