import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    scrollContent: {
        paddingBottom: 40,
    },
    loader: {
        marginTop: 100,
    },
    summaryBanner: {
        backgroundColor: '#4361EE',
        paddingHorizontal: 24,
        paddingTop: 24,
        paddingBottom: 36,
    },
    summaryBannerTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: 'rgba(255,255,255,0.7)',
        marginBottom: 4,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    summaryBannerCount: {
        fontSize: 36,
        fontWeight: '800',
        color: '#FFFFFF',
        letterSpacing: -1,
        marginBottom: 24,
    },
    summaryStatsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    summaryStatBox: {
        flex: 1,
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 14,
        padding: 14,
    },
    summaryStatLabel: {
        fontSize: 11,
        color: 'rgba(255,255,255,0.7)',
        fontWeight: '600',
        marginBottom: 6,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    summaryStatValue: {
        fontSize: 20,
        fontWeight: '800',
        color: '#FFFFFF',
    },
    listSection: {
        paddingHorizontal: 20,
        marginTop: -18,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1A1A1A',
    },
    groupCountBadge: {
        backgroundColor: '#EBF0FF',
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 4,
    },
    groupCountBadgeText: {
        fontSize: 13,
        fontWeight: '700',
        color: '#4361EE',
    },
    createGroupCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F0F3FF',
        borderRadius: 18,
        padding: 18,
        marginBottom: 14,
        borderWidth: 1.5,
        borderColor: '#C7D2FE',
        borderStyle: 'dashed',
    },
    createIconBubble: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#4361EE',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    createIconText: {
        fontSize: 28,
        color: '#FFFFFF',
        fontWeight: '300',
        lineHeight: 32,
    },
    createTextBlock: {
        flex: 1,
    },
    createGroupTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#4361EE',
        marginBottom: 2,
    },
    createGroupSubtitle: {
        fontSize: 12,
        color: '#7C8DB5',
        fontWeight: '500',
    },
    createArrow: {
        fontSize: 22,
        color: '#4361EE',
        fontWeight: '600',
    },
    groupCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        marginBottom: 14,
        overflow: 'hidden',
        shadowColor: '#4361EE',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.06,
        shadowRadius: 12,
        elevation: 3,
    },
    cardAccentBar: {
        height: 4,
        width: '100%',
    },
    cardBody: {
        padding: 18,
    },
    cardTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    groupIconBubble: {
        width: 52,
        height: 52,
        borderRadius: 16,
        backgroundColor: '#F0F3FF',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
    },
    groupIconImg: {
        width: 30,
        height: 30,
        tintColor: '#4361EE',
    },
    groupTitleBlock: {
        flex: 1,
    },
    groupName: {
        fontSize: 17,
        fontWeight: '700',
        color: '#1A1A1A',
        marginBottom: 3,
    },
    memberCount: {
        fontSize: 12,
        color: '#888888',
        fontWeight: '500',
    },
    totalExpenseContainer: {
        alignItems: 'flex-end',
    },
    totalExpenseLabel: {
        fontSize: 11,
        color: '#888888',
        fontWeight: '500',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 3,
    },
    totalExpense: {
        fontSize: 20,
        fontWeight: '800',
        color: '#1A1A1A',
        letterSpacing: -0.5,
    },
    separator: {
        height: 1,
        backgroundColor: '#F3F4F8',
        marginBottom: 14,
    },
    cardBottomRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    balanceBlock: {
        flex: 1,
    },
    balanceLabel: {
        fontSize: 11,
        color: '#888888',
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 4,
    },
    balanceValue: {
        fontSize: 16,
        fontWeight: '700',
    },
    settledBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#E8FFF2',
        borderRadius: 10,
        paddingVertical: 6,
        paddingHorizontal: 12,
        alignSelf: 'flex-start',
    },
    settledBadgeText: {
        color: '#28a745',
        fontSize: 13,
        fontWeight: '700',
    },
    emptyStateContainer: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    emptyStateIcon: {
        fontSize: 48,
        marginBottom: 16,
    },
    emptyStateTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1A1A1A',
        marginBottom: 8,
    },
    emptyStateSubtitle: {
        fontSize: 14,
        color: '#888888',
        textAlign: 'center',
        lineHeight: 20,
    },
});
