import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F8F9FA",
    },

    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 40,
    },
    profileHeaderCard: {
        alignItems: "center",
        paddingVertical: 25,
        marginVertical: 10,
    },
    avatarWrapper: {
        position: "relative",
        shadowColor: "#4361EE",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.15,
        shadowRadius: 16,
        elevation: 6,
    },
    avatarEditBadge: {
        position: "absolute",
        bottom: -2,
        right: -2,
        backgroundColor: "#4361EE",
        width: 32,
        height: 32,
        borderRadius: 16,
        borderWidth: 3,
        borderColor: "#FFFFFF",
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    avatarEditIcon: {
        fontSize: 12,
        color: "#FFFFFF",
    },
    userName: {
        fontSize: 24,
        fontWeight: "800",
        color: "#1A1A1A",
        marginTop: 16,
        letterSpacing: -0.5,
    },
    userEmail: {
        fontSize: 14,
        color: "#666666",
        marginTop: 4,
        fontWeight: "500",
    },
    balanceCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 24,
        padding: 20,
        marginBottom: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.04,
        shadowRadius: 12,
        elevation: 3,
    },
    balanceTitle: {
        fontSize: 13,
        color: "#888888",
        fontWeight: "600",
        textAlign: "center",
        textTransform: "uppercase",
        letterSpacing: 0.8,
    },
    balanceValue: {
        fontSize: 32,
        fontWeight: "800",
        textAlign: "center",
        marginVertical: 10,
        letterSpacing: -0.5,
    },
    balanceSplitRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "#F8F9FA",
        borderRadius: 16,
        padding: 12,
        marginTop: 6,
    },
    balanceSubItem: {
        flex: 1,
        alignItems: "center",
    },
    balanceSubTitle: {
        fontSize: 12,
        color: "#888888",
        fontWeight: "600",
    },
    balanceOwedValue: {
        fontSize: 16,
        fontWeight: "700",
        color: "#2EC4B6",
        marginTop: 4,
    },
    balanceOweValue: {
        fontSize: 16,
        fontWeight: "700",
        color: "#E63946",
        marginTop: 4,
    },
    balanceDivider: {
        width: 1,
        height: 24,
        backgroundColor: "#E0E0E0",
    },
    actionsCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 24,
        padding: 18,
        marginBottom: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.04,
        shadowRadius: 12,
        elevation: 3,
    },

    sectionHeader: {
        fontSize: 11,
        color: "#888888",
        fontWeight: "700",
        textTransform: "uppercase",
        letterSpacing: 1.2,
        marginBottom: 10,
    },
    actionRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 14,
    },
    actionLabelContainer: {
        flexDirection: "row",
        alignItems: "center",
        gap: 14,
    },
    actionIcon: {
        fontSize: 18,
        width: 24,
        textAlign: "center",
    },
    actionLabel: {
        fontSize: 15,
        fontWeight: "600",
        color: "#2B2D42",
    },
    arrowIcon: {
        fontSize: 18,
        color: "#BCC2CD",
        fontWeight: "600",
    },
    logoutText: {
        color: "#E63946",
    },
    deleteText: {
        color: "#E63946",
        opacity: 0.8,
    },
    footerContainer: {
        alignItems: "center",
        marginTop: 10,
        marginBottom: 20,
    },
    footerText: {
        fontSize: 11,
        color: "#A0A0A0",
        fontWeight: "600",
    },
    footerSubText: {
        fontSize: 9,
        color: "#CCCCCC",
        marginTop: 2,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.4)",
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
    },
    modalContainer: {
        backgroundColor: "#FFFFFF",
        borderRadius: 28,
        padding: 24,
        width: "100%",
        maxWidth: 340,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.12,
        shadowRadius: 20,
        elevation: 8,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: "800",
        color: "#1A1A1A",
        marginBottom: 8,
        textAlign: "center",
        letterSpacing: -0.5,
    },
    modalSubtitle: {
        fontSize: 13,
        color: "#666666",
        textAlign: "center",
        marginBottom: 20,
        lineHeight: 18,
    },
    modalInput: {
        borderWidth: 1,
        borderColor: "#EAEAEA",
        borderRadius: 14,
        paddingVertical: 12,
        paddingHorizontal: 16,
        fontSize: 15,
        color: "#333333",
        marginBottom: 16,
        backgroundColor: "#F8F9FA",
    },
    modalButtonRow: {
        flexDirection: "row",
        gap: 12,
        marginTop: 8,
    },
    modalButton: {
        flex: 1,
        paddingVertical: 13,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
    },
    modalCancelButton: {
        backgroundColor: "#F1F3F5",
    },
    modalCancelButtonText: {
        color: "#4E5969",
        fontWeight: "700",
        fontSize: 14,
    },
    modalSaveButton: {
        backgroundColor: "#4361EE",
    },
    modalSaveButtonText: {
        color: "#FFFFFF",
        fontWeight: "700",
        fontSize: 14,
    },
});

export default styles;